// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// AddReader is a Reader for the Add structure.
type AddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAddDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAddOK creates a AddOK with default headers values
func NewAddOK() *AddOK {
	return &AddOK{}
}

/*
AddOK describes a response with status code 200, with default header values.

add customer service account response
*/
type AddOK struct {
	Payload *models.AddCustomerServiceAccountReponse
}

// IsSuccess returns true when this add o k response has a 2xx status code
func (o *AddOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add o k response has a 3xx status code
func (o *AddOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add o k response has a 4xx status code
func (o *AddOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add o k response has a 5xx status code
func (o *AddOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add o k response a status code equal to that given
func (o *AddOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add o k response
func (o *AddOK) Code() int {
	return 200
}

func (o *AddOK) Error() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] addOK  %+v", 200, o.Payload)
}

func (o *AddOK) String() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] addOK  %+v", 200, o.Payload)
}

func (o *AddOK) GetPayload() *models.AddCustomerServiceAccountReponse {
	return o.Payload
}

func (o *AddOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddCustomerServiceAccountReponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddDefault creates a AddDefault with default headers values
func NewAddDefault(code int) *AddDefault {
	return &AddDefault{
		_statusCode: code,
	}
}

/*
AddDefault describes a response with status code -1, with default header values.

unexpected error
*/
type AddDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this add default response has a 2xx status code
func (o *AddDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this add default response has a 3xx status code
func (o *AddDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this add default response has a 4xx status code
func (o *AddDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this add default response has a 5xx status code
func (o *AddDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this add default response a status code equal to that given
func (o *AddDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the add default response
func (o *AddDefault) Code() int {
	return o._statusCode
}

func (o *AddDefault) Error() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] add default  %+v", o._statusCode, o.Payload)
}

func (o *AddDefault) String() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] add default  %+v", o._statusCode, o.Payload)
}

func (o *AddDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *AddDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
