// Code generated by go-swagger; DO NOT EDIT.

package service_state

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// NewTransformParams creates a new TransformParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTransformParams() *TransformParams {
	return &TransformParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTransformParamsWithTimeout creates a new TransformParams object
// with the ability to set a timeout on a request.
func NewTransformParamsWithTimeout(timeout time.Duration) *TransformParams {
	return &TransformParams{
		timeout: timeout,
	}
}

// NewTransformParamsWithContext creates a new TransformParams object
// with the ability to set a context for a request.
func NewTransformParamsWithContext(ctx context.Context) *TransformParams {
	return &TransformParams{
		Context: ctx,
	}
}

// NewTransformParamsWithHTTPClient creates a new TransformParams object
// with the ability to set a custom HTTPClient for a request.
func NewTransformParamsWithHTTPClient(client *http.Client) *TransformParams {
	return &TransformParams{
		HTTPClient: client,
	}
}

/*
TransformParams contains all the parameters to send to the API endpoint

	for the transform operation.

	Typically these are written to a http.Request.
*/
type TransformParams struct {

	/* TransformServiceStateRequest.

	   transform service state request
	*/
	TransformServiceStateRequest *models.TransformServiceStateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the transform params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransformParams) WithDefaults() *TransformParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the transform params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransformParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the transform params
func (o *TransformParams) WithTimeout(timeout time.Duration) *TransformParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transform params
func (o *TransformParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transform params
func (o *TransformParams) WithContext(ctx context.Context) *TransformParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transform params
func (o *TransformParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transform params
func (o *TransformParams) WithHTTPClient(client *http.Client) *TransformParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transform params
func (o *TransformParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTransformServiceStateRequest adds the transformServiceStateRequest to the transform params
func (o *TransformParams) WithTransformServiceStateRequest(transformServiceStateRequest *models.TransformServiceStateRequest) *TransformParams {
	o.SetTransformServiceStateRequest(transformServiceStateRequest)
	return o
}

// SetTransformServiceStateRequest adds the transformServiceStateRequest to the transform params
func (o *TransformParams) SetTransformServiceStateRequest(transformServiceStateRequest *models.TransformServiceStateRequest) {
	o.TransformServiceStateRequest = transformServiceStateRequest
}

// WriteToRequest writes these params to a swagger request
func (o *TransformParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.TransformServiceStateRequest != nil {
		if err := r.SetBodyParam(o.TransformServiceStateRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
