// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// NewSendParams creates a new SendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSendParams() *SendParams {
	return &SendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSendParamsWithTimeout creates a new SendParams object
// with the ability to set a timeout on a request.
func NewSendParamsWithTimeout(timeout time.Duration) *SendParams {
	return &SendParams{
		timeout: timeout,
	}
}

// NewSendParamsWithContext creates a new SendParams object
// with the ability to set a context for a request.
func NewSendParamsWithContext(ctx context.Context) *SendParams {
	return &SendParams{
		Context: ctx,
	}
}

// NewSendParamsWithHTTPClient creates a new SendParams object
// with the ability to set a custom HTTPClient for a request.
func NewSendParamsWithHTTPClient(client *http.Client) *SendParams {
	return &SendParams{
		HTTPClient: client,
	}
}

/*
SendParams contains all the parameters to send to the API endpoint

	for the send operation.

	Typically these are written to a http.Request.
*/
type SendParams struct {

	/* SendRequest.

	   send message request
	*/
	SendRequest *models.SendRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendParams) WithDefaults() *SendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the send params
func (o *SendParams) WithTimeout(timeout time.Duration) *SendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send params
func (o *SendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send params
func (o *SendParams) WithContext(ctx context.Context) *SendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send params
func (o *SendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send params
func (o *SendParams) WithHTTPClient(client *http.Client) *SendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send params
func (o *SendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSendRequest adds the sendRequest to the send params
func (o *SendParams) WithSendRequest(sendRequest *models.SendRequest) *SendParams {
	o.SetSendRequest(sendRequest)
	return o
}

// SetSendRequest adds the sendRequest to the send params
func (o *SendParams) SetSendRequest(sendRequest *models.SendRequest) {
	o.SendRequest = sendRequest
}

// WriteToRequest writes these params to a swagger request
func (o *SendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.SendRequest != nil {
		if err := r.SetBodyParam(o.SendRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
