// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// NewSyncParams creates a new SyncParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSyncParams() *SyncParams {
	return &SyncParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSyncParamsWithTimeout creates a new SyncParams object
// with the ability to set a timeout on a request.
func NewSyncParamsWithTimeout(timeout time.Duration) *SyncParams {
	return &SyncParams{
		timeout: timeout,
	}
}

// NewSyncParamsWithContext creates a new SyncParams object
// with the ability to set a context for a request.
func NewSyncParamsWithContext(ctx context.Context) *SyncParams {
	return &SyncParams{
		Context: ctx,
	}
}

// NewSyncParamsWithHTTPClient creates a new SyncParams object
// with the ability to set a custom HTTPClient for a request.
func NewSyncParamsWithHTTPClient(client *http.Client) *SyncParams {
	return &SyncParams{
		HTTPClient: client,
	}
}

/*
SyncParams contains all the parameters to send to the API endpoint

	for the sync operation.

	Typically these are written to a http.Request.
*/
type SyncParams struct {

	/* SyncRequest.

	   sync message request
	*/
	SyncRequest *models.SyncRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the sync params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SyncParams) WithDefaults() *SyncParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the sync params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SyncParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the sync params
func (o *SyncParams) WithTimeout(timeout time.Duration) *SyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sync params
func (o *SyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sync params
func (o *SyncParams) WithContext(ctx context.Context) *SyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sync params
func (o *SyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sync params
func (o *SyncParams) WithHTTPClient(client *http.Client) *SyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sync params
func (o *SyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSyncRequest adds the syncRequest to the sync params
func (o *SyncParams) WithSyncRequest(syncRequest *models.SyncRequest) *SyncParams {
	o.SetSyncRequest(syncRequest)
	return o
}

// SetSyncRequest adds the syncRequest to the sync params
func (o *SyncParams) SetSyncRequest(syncRequest *models.SyncRequest) {
	o.SyncRequest = syncRequest
}

// WriteToRequest writes these params to a swagger request
func (o *SyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.SyncRequest != nil {
		if err := r.SetBodyParam(o.SyncRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
