// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// NewAddCustomerServiceAccountParams creates a new AddCustomerServiceAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddCustomerServiceAccountParams() *AddCustomerServiceAccountParams {
	return &AddCustomerServiceAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddCustomerServiceAccountParamsWithTimeout creates a new AddCustomerServiceAccountParams object
// with the ability to set a timeout on a request.
func NewAddCustomerServiceAccountParamsWithTimeout(timeout time.Duration) *AddCustomerServiceAccountParams {
	return &AddCustomerServiceAccountParams{
		timeout: timeout,
	}
}

// NewAddCustomerServiceAccountParamsWithContext creates a new AddCustomerServiceAccountParams object
// with the ability to set a context for a request.
func NewAddCustomerServiceAccountParamsWithContext(ctx context.Context) *AddCustomerServiceAccountParams {
	return &AddCustomerServiceAccountParams{
		Context: ctx,
	}
}

// NewAddCustomerServiceAccountParamsWithHTTPClient creates a new AddCustomerServiceAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddCustomerServiceAccountParamsWithHTTPClient(client *http.Client) *AddCustomerServiceAccountParams {
	return &AddCustomerServiceAccountParams{
		HTTPClient: client,
	}
}

/*
AddCustomerServiceAccountParams contains all the parameters to send to the API endpoint

	for the add customer service account operation.

	Typically these are written to a http.Request.
*/
type AddCustomerServiceAccountParams struct {

	/* AddCustomerServiceAccountRequest.

	   add customer service account request
	*/
	AddCustomerServiceAccountRequest *models.AddCustomerServiceAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add customer service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCustomerServiceAccountParams) WithDefaults() *AddCustomerServiceAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add customer service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCustomerServiceAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add customer service account params
func (o *AddCustomerServiceAccountParams) WithTimeout(timeout time.Duration) *AddCustomerServiceAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add customer service account params
func (o *AddCustomerServiceAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add customer service account params
func (o *AddCustomerServiceAccountParams) WithContext(ctx context.Context) *AddCustomerServiceAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add customer service account params
func (o *AddCustomerServiceAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add customer service account params
func (o *AddCustomerServiceAccountParams) WithHTTPClient(client *http.Client) *AddCustomerServiceAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add customer service account params
func (o *AddCustomerServiceAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddCustomerServiceAccountRequest adds the addCustomerServiceAccountRequest to the add customer service account params
func (o *AddCustomerServiceAccountParams) WithAddCustomerServiceAccountRequest(addCustomerServiceAccountRequest *models.AddCustomerServiceAccountRequest) *AddCustomerServiceAccountParams {
	o.SetAddCustomerServiceAccountRequest(addCustomerServiceAccountRequest)
	return o
}

// SetAddCustomerServiceAccountRequest adds the addCustomerServiceAccountRequest to the add customer service account params
func (o *AddCustomerServiceAccountParams) SetAddCustomerServiceAccountRequest(addCustomerServiceAccountRequest *models.AddCustomerServiceAccountRequest) {
	o.AddCustomerServiceAccountRequest = addCustomerServiceAccountRequest
}

// WriteToRequest writes these params to a swagger request
func (o *AddCustomerServiceAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.AddCustomerServiceAccountRequest != nil {
		if err := r.SetBodyParam(o.AddCustomerServiceAccountRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
