// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// AddCustomerServiceAccountReader is a Reader for the AddCustomerServiceAccount structure.
type AddCustomerServiceAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddCustomerServiceAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddCustomerServiceAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAddCustomerServiceAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAddCustomerServiceAccountOK creates a AddCustomerServiceAccountOK with default headers values
func NewAddCustomerServiceAccountOK() *AddCustomerServiceAccountOK {
	return &AddCustomerServiceAccountOK{}
}

/*
AddCustomerServiceAccountOK describes a response with status code 200, with default header values.

add customer service account response
*/
type AddCustomerServiceAccountOK struct {
	Payload *models.AddCustomerServiceAccountReponse
}

// IsSuccess returns true when this add customer service account o k response has a 2xx status code
func (o *AddCustomerServiceAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add customer service account o k response has a 3xx status code
func (o *AddCustomerServiceAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add customer service account o k response has a 4xx status code
func (o *AddCustomerServiceAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add customer service account o k response has a 5xx status code
func (o *AddCustomerServiceAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add customer service account o k response a status code equal to that given
func (o *AddCustomerServiceAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add customer service account o k response
func (o *AddCustomerServiceAccountOK) Code() int {
	return 200
}

func (o *AddCustomerServiceAccountOK) Error() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] addCustomerServiceAccountOK  %+v", 200, o.Payload)
}

func (o *AddCustomerServiceAccountOK) String() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] addCustomerServiceAccountOK  %+v", 200, o.Payload)
}

func (o *AddCustomerServiceAccountOK) GetPayload() *models.AddCustomerServiceAccountReponse {
	return o.Payload
}

func (o *AddCustomerServiceAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddCustomerServiceAccountReponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddCustomerServiceAccountDefault creates a AddCustomerServiceAccountDefault with default headers values
func NewAddCustomerServiceAccountDefault(code int) *AddCustomerServiceAccountDefault {
	return &AddCustomerServiceAccountDefault{
		_statusCode: code,
	}
}

/*
AddCustomerServiceAccountDefault describes a response with status code -1, with default header values.

unexpected error
*/
type AddCustomerServiceAccountDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this add customer service account default response has a 2xx status code
func (o *AddCustomerServiceAccountDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this add customer service account default response has a 3xx status code
func (o *AddCustomerServiceAccountDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this add customer service account default response has a 4xx status code
func (o *AddCustomerServiceAccountDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this add customer service account default response has a 5xx status code
func (o *AddCustomerServiceAccountDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this add customer service account default response a status code equal to that given
func (o *AddCustomerServiceAccountDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the add customer service account default response
func (o *AddCustomerServiceAccountDefault) Code() int {
	return o._statusCode
}

func (o *AddCustomerServiceAccountDefault) Error() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] addCustomerServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *AddCustomerServiceAccountDefault) String() string {
	return fmt.Sprintf("[POST /kf/account/add][%d] addCustomerServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *AddCustomerServiceAccountDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *AddCustomerServiceAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
