// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// DelCustomerServiceAccountReader is a Reader for the DelCustomerServiceAccount structure.
type DelCustomerServiceAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DelCustomerServiceAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDelCustomerServiceAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDelCustomerServiceAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDelCustomerServiceAccountOK creates a DelCustomerServiceAccountOK with default headers values
func NewDelCustomerServiceAccountOK() *DelCustomerServiceAccountOK {
	return &DelCustomerServiceAccountOK{}
}

/*
DelCustomerServiceAccountOK describes a response with status code 200, with default header values.

delete customer service account response
*/
type DelCustomerServiceAccountOK struct {
	Payload *models.DelCustomerServiceAccountReponse
}

// IsSuccess returns true when this del customer service account o k response has a 2xx status code
func (o *DelCustomerServiceAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this del customer service account o k response has a 3xx status code
func (o *DelCustomerServiceAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del customer service account o k response has a 4xx status code
func (o *DelCustomerServiceAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this del customer service account o k response has a 5xx status code
func (o *DelCustomerServiceAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this del customer service account o k response a status code equal to that given
func (o *DelCustomerServiceAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the del customer service account o k response
func (o *DelCustomerServiceAccountOK) Code() int {
	return 200
}

func (o *DelCustomerServiceAccountOK) Error() string {
	return fmt.Sprintf("[POST /kf/account/del][%d] delCustomerServiceAccountOK  %+v", 200, o.Payload)
}

func (o *DelCustomerServiceAccountOK) String() string {
	return fmt.Sprintf("[POST /kf/account/del][%d] delCustomerServiceAccountOK  %+v", 200, o.Payload)
}

func (o *DelCustomerServiceAccountOK) GetPayload() *models.DelCustomerServiceAccountReponse {
	return o.Payload
}

func (o *DelCustomerServiceAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DelCustomerServiceAccountReponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDelCustomerServiceAccountDefault creates a DelCustomerServiceAccountDefault with default headers values
func NewDelCustomerServiceAccountDefault(code int) *DelCustomerServiceAccountDefault {
	return &DelCustomerServiceAccountDefault{
		_statusCode: code,
	}
}

/*
DelCustomerServiceAccountDefault describes a response with status code -1, with default header values.

unexpected error
*/
type DelCustomerServiceAccountDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this del customer service account default response has a 2xx status code
func (o *DelCustomerServiceAccountDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this del customer service account default response has a 3xx status code
func (o *DelCustomerServiceAccountDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this del customer service account default response has a 4xx status code
func (o *DelCustomerServiceAccountDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this del customer service account default response has a 5xx status code
func (o *DelCustomerServiceAccountDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this del customer service account default response a status code equal to that given
func (o *DelCustomerServiceAccountDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the del customer service account default response
func (o *DelCustomerServiceAccountDefault) Code() int {
	return o._statusCode
}

func (o *DelCustomerServiceAccountDefault) Error() string {
	return fmt.Sprintf("[POST /kf/account/del][%d] delCustomerServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *DelCustomerServiceAccountDefault) String() string {
	return fmt.Sprintf("[POST /kf/account/del][%d] delCustomerServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *DelCustomerServiceAccountDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *DelCustomerServiceAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
