// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// ListCustomerServiceAccountReader is a Reader for the ListCustomerServiceAccount structure.
type ListCustomerServiceAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCustomerServiceAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCustomerServiceAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListCustomerServiceAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListCustomerServiceAccountOK creates a ListCustomerServiceAccountOK with default headers values
func NewListCustomerServiceAccountOK() *ListCustomerServiceAccountOK {
	return &ListCustomerServiceAccountOK{}
}

/*
ListCustomerServiceAccountOK describes a response with status code 200, with default header values.

list customer service account response
*/
type ListCustomerServiceAccountOK struct {
	Payload *models.ListCustomerServiceAccountReponse
}

// IsSuccess returns true when this list customer service account o k response has a 2xx status code
func (o *ListCustomerServiceAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list customer service account o k response has a 3xx status code
func (o *ListCustomerServiceAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list customer service account o k response has a 4xx status code
func (o *ListCustomerServiceAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list customer service account o k response has a 5xx status code
func (o *ListCustomerServiceAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list customer service account o k response a status code equal to that given
func (o *ListCustomerServiceAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list customer service account o k response
func (o *ListCustomerServiceAccountOK) Code() int {
	return 200
}

func (o *ListCustomerServiceAccountOK) Error() string {
	return fmt.Sprintf("[POST /kf/account/list][%d] listCustomerServiceAccountOK  %+v", 200, o.Payload)
}

func (o *ListCustomerServiceAccountOK) String() string {
	return fmt.Sprintf("[POST /kf/account/list][%d] listCustomerServiceAccountOK  %+v", 200, o.Payload)
}

func (o *ListCustomerServiceAccountOK) GetPayload() *models.ListCustomerServiceAccountReponse {
	return o.Payload
}

func (o *ListCustomerServiceAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListCustomerServiceAccountReponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListCustomerServiceAccountDefault creates a ListCustomerServiceAccountDefault with default headers values
func NewListCustomerServiceAccountDefault(code int) *ListCustomerServiceAccountDefault {
	return &ListCustomerServiceAccountDefault{
		_statusCode: code,
	}
}

/*
ListCustomerServiceAccountDefault describes a response with status code -1, with default header values.

unexpected error
*/
type ListCustomerServiceAccountDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this list customer service account default response has a 2xx status code
func (o *ListCustomerServiceAccountDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list customer service account default response has a 3xx status code
func (o *ListCustomerServiceAccountDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list customer service account default response has a 4xx status code
func (o *ListCustomerServiceAccountDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list customer service account default response has a 5xx status code
func (o *ListCustomerServiceAccountDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list customer service account default response a status code equal to that given
func (o *ListCustomerServiceAccountDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list customer service account default response
func (o *ListCustomerServiceAccountDefault) Code() int {
	return o._statusCode
}

func (o *ListCustomerServiceAccountDefault) Error() string {
	return fmt.Sprintf("[POST /kf/account/list][%d] listCustomerServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *ListCustomerServiceAccountDefault) String() string {
	return fmt.Sprintf("[POST /kf/account/list][%d] listCustomerServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *ListCustomerServiceAccountDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *ListCustomerServiceAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
