// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// NewListCustomerServiceAccountParams creates a new ListCustomerServiceAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListCustomerServiceAccountParams() *ListCustomerServiceAccountParams {
	return &ListCustomerServiceAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListCustomerServiceAccountParamsWithTimeout creates a new ListCustomerServiceAccountParams object
// with the ability to set a timeout on a request.
func NewListCustomerServiceAccountParamsWithTimeout(timeout time.Duration) *ListCustomerServiceAccountParams {
	return &ListCustomerServiceAccountParams{
		timeout: timeout,
	}
}

// NewListCustomerServiceAccountParamsWithContext creates a new ListCustomerServiceAccountParams object
// with the ability to set a context for a request.
func NewListCustomerServiceAccountParamsWithContext(ctx context.Context) *ListCustomerServiceAccountParams {
	return &ListCustomerServiceAccountParams{
		Context: ctx,
	}
}

// NewListCustomerServiceAccountParamsWithHTTPClient creates a new ListCustomerServiceAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewListCustomerServiceAccountParamsWithHTTPClient(client *http.Client) *ListCustomerServiceAccountParams {
	return &ListCustomerServiceAccountParams{
		HTTPClient: client,
	}
}

/*
ListCustomerServiceAccountParams contains all the parameters to send to the API endpoint

	for the list customer service account operation.

	Typically these are written to a http.Request.
*/
type ListCustomerServiceAccountParams struct {

	/* ListCustomerServiceAccountRequest.

	   list customer service account request
	*/
	ListCustomerServiceAccountRequest *models.ListCustomerServiceAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list customer service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCustomerServiceAccountParams) WithDefaults() *ListCustomerServiceAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list customer service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCustomerServiceAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list customer service account params
func (o *ListCustomerServiceAccountParams) WithTimeout(timeout time.Duration) *ListCustomerServiceAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list customer service account params
func (o *ListCustomerServiceAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list customer service account params
func (o *ListCustomerServiceAccountParams) WithContext(ctx context.Context) *ListCustomerServiceAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list customer service account params
func (o *ListCustomerServiceAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list customer service account params
func (o *ListCustomerServiceAccountParams) WithHTTPClient(client *http.Client) *ListCustomerServiceAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list customer service account params
func (o *ListCustomerServiceAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithListCustomerServiceAccountRequest adds the listCustomerServiceAccountRequest to the list customer service account params
func (o *ListCustomerServiceAccountParams) WithListCustomerServiceAccountRequest(listCustomerServiceAccountRequest *models.ListCustomerServiceAccountRequest) *ListCustomerServiceAccountParams {
	o.SetListCustomerServiceAccountRequest(listCustomerServiceAccountRequest)
	return o
}

// SetListCustomerServiceAccountRequest adds the listCustomerServiceAccountRequest to the list customer service account params
func (o *ListCustomerServiceAccountParams) SetListCustomerServiceAccountRequest(listCustomerServiceAccountRequest *models.ListCustomerServiceAccountRequest) {
	o.ListCustomerServiceAccountRequest = listCustomerServiceAccountRequest
}

// WriteToRequest writes these params to a swagger request
func (o *ListCustomerServiceAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ListCustomerServiceAccountRequest != nil {
		if err := r.SetBodyParam(o.ListCustomerServiceAccountRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
