// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/wecom/models"
)

// NewUpdateCustomerServiceAccountParams creates a new UpdateCustomerServiceAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateCustomerServiceAccountParams() *UpdateCustomerServiceAccountParams {
	return &UpdateCustomerServiceAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCustomerServiceAccountParamsWithTimeout creates a new UpdateCustomerServiceAccountParams object
// with the ability to set a timeout on a request.
func NewUpdateCustomerServiceAccountParamsWithTimeout(timeout time.Duration) *UpdateCustomerServiceAccountParams {
	return &UpdateCustomerServiceAccountParams{
		timeout: timeout,
	}
}

// NewUpdateCustomerServiceAccountParamsWithContext creates a new UpdateCustomerServiceAccountParams object
// with the ability to set a context for a request.
func NewUpdateCustomerServiceAccountParamsWithContext(ctx context.Context) *UpdateCustomerServiceAccountParams {
	return &UpdateCustomerServiceAccountParams{
		Context: ctx,
	}
}

// NewUpdateCustomerServiceAccountParamsWithHTTPClient creates a new UpdateCustomerServiceAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateCustomerServiceAccountParamsWithHTTPClient(client *http.Client) *UpdateCustomerServiceAccountParams {
	return &UpdateCustomerServiceAccountParams{
		HTTPClient: client,
	}
}

/*
UpdateCustomerServiceAccountParams contains all the parameters to send to the API endpoint

	for the update customer service account operation.

	Typically these are written to a http.Request.
*/
type UpdateCustomerServiceAccountParams struct {

	/* UpdateCustomerServiceAccountRequest.

	   update customer service account request
	*/
	UpdateCustomerServiceAccountRequest *models.UpdateCustomerServiceAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update customer service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCustomerServiceAccountParams) WithDefaults() *UpdateCustomerServiceAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update customer service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCustomerServiceAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) WithTimeout(timeout time.Duration) *UpdateCustomerServiceAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) WithContext(ctx context.Context) *UpdateCustomerServiceAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) WithHTTPClient(client *http.Client) *UpdateCustomerServiceAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateCustomerServiceAccountRequest adds the updateCustomerServiceAccountRequest to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) WithUpdateCustomerServiceAccountRequest(updateCustomerServiceAccountRequest *models.UpdateCustomerServiceAccountRequest) *UpdateCustomerServiceAccountParams {
	o.SetUpdateCustomerServiceAccountRequest(updateCustomerServiceAccountRequest)
	return o
}

// SetUpdateCustomerServiceAccountRequest adds the updateCustomerServiceAccountRequest to the update customer service account params
func (o *UpdateCustomerServiceAccountParams) SetUpdateCustomerServiceAccountRequest(updateCustomerServiceAccountRequest *models.UpdateCustomerServiceAccountRequest) {
	o.UpdateCustomerServiceAccountRequest = updateCustomerServiceAccountRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCustomerServiceAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.UpdateCustomerServiceAccountRequest != nil {
		if err := r.SetBodyParam(o.UpdateCustomerServiceAccountRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
