// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddCustomerServiceAccountRequest add customer service account request
//
// swagger:model AddCustomerServiceAccountRequest
type AddCustomerServiceAccountRequest struct {

	// media id
	// Required: true
	MediaID *string `json:"media_id"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this add customer service account request
func (m *AddCustomerServiceAccountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediaID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddCustomerServiceAccountRequest) validateMediaID(formats strfmt.Registry) error {

	if err := validate.Required("media_id", "body", m.MediaID); err != nil {
		return err
	}

	return nil
}

func (m *AddCustomerServiceAccountRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this add customer service account request based on context it is used
func (m *AddCustomerServiceAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddCustomerServiceAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddCustomerServiceAccountRequest) UnmarshalBinary(b []byte) error {
	var res AddCustomerServiceAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
