// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CustomerServiceAccount customer service account
//
// swagger:model CustomerServiceAccount
type CustomerServiceAccount struct {

	// avatar
	// Required: true
	Avatar *string `json:"avatar"`

	// name
	// Required: true
	Name *string `json:"name"`

	// open kfid
	// Required: true
	OpenKfid *string `json:"open_kfid"`
}

// Validate validates this customer service account
func (m *CustomerServiceAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvatar(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpenKfid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustomerServiceAccount) validateAvatar(formats strfmt.Registry) error {

	if err := validate.Required("avatar", "body", m.Avatar); err != nil {
		return err
	}

	return nil
}

func (m *CustomerServiceAccount) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *CustomerServiceAccount) validateOpenKfid(formats strfmt.Registry) error {

	if err := validate.Required("open_kfid", "body", m.OpenKfid); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this customer service account based on context it is used
func (m *CustomerServiceAccount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomerServiceAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomerServiceAccount) UnmarshalBinary(b []byte) error {
	var res CustomerServiceAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
