// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetServiceStateRequest get service state request
//
// swagger:model GetServiceStateRequest
type GetServiceStateRequest struct {

	// external userid
	// Required: true
	ExternalUserid *string `json:"external_userid"`

	// open kfid
	// Required: true
	OpenKfid *string `json:"open_kfid"`
}

// Validate validates this get service state request
func (m *GetServiceStateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExternalUserid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpenKfid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetServiceStateRequest) validateExternalUserid(formats strfmt.Registry) error {

	if err := validate.Required("external_userid", "body", m.ExternalUserid); err != nil {
		return err
	}

	return nil
}

func (m *GetServiceStateRequest) validateOpenKfid(formats strfmt.Registry) error {

	if err := validate.Required("open_kfid", "body", m.OpenKfid); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get service state request based on context it is used
func (m *GetServiceStateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetServiceStateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetServiceStateRequest) UnmarshalBinary(b []byte) error {
	var res GetServiceStateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
