// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListCustomerServiceAccountRequest list customer service account request
//
// swagger:model ListCustomerServiceAccountRequest
type ListCustomerServiceAccountRequest struct {

	// limit
	Limit int32 `json:"limit,omitempty"`

	// offset
	Offset int32 `json:"offset,omitempty"`
}

// Validate validates this list customer service account request
func (m *ListCustomerServiceAccountRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list customer service account request based on context it is used
func (m *ListCustomerServiceAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListCustomerServiceAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListCustomerServiceAccountRequest) UnmarshalBinary(b []byte) error {
	var res ListCustomerServiceAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
