// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Message message
//
// swagger:model Message
type Message struct {

	// external userid
	ExternalUserid string `json:"external_userid,omitempty"`

	// msgid
	Msgid string `json:"msgid,omitempty"`

	// msgtype
	Msgtype string `json:"msgtype,omitempty"`

	// open kfid
	OpenKfid string `json:"open_kfid,omitempty"`

	// origin
	Origin int32 `json:"origin,omitempty"`

	// send time
	SendTime int64 `json:"send_time,omitempty"`
}

// Validate validates this message
func (m *Message) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this message based on context it is used
func (m *Message) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Message) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Message) UnmarshalBinary(b []byte) error {
	var res Message
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
