// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SyncRequest sync request
//
// swagger:model SyncRequest
type SyncRequest struct {

	// cursor
	Cursor string `json:"cursor,omitempty"`

	// limit
	Limit uint32 `json:"limit,omitempty"`

	// open kfid
	OpenKfid string `json:"open_kfid,omitempty"`

	// token
	Token string `json:"token,omitempty"`

	// voice format
	VoiceFormat uint32 `json:"voice_format,omitempty"`
}

// Validate validates this sync request
func (m *SyncRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sync request based on context it is used
func (m *SyncRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SyncRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyncRequest) UnmarshalBinary(b []byte) error {
	var res SyncRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
