// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransformServiceStateRequest transform service state request
//
// swagger:model TransformServiceStateRequest
type TransformServiceStateRequest struct {

	// external userid
	// Required: true
	ExternalUserid *string `json:"external_userid"`

	// open kfid
	// Required: true
	OpenKfid *string `json:"open_kfid"`

	// service state
	// Required: true
	ServiceState *int32 `json:"service_state"`

	// servicer userid
	ServicerUserid string `json:"servicer_userid,omitempty"`
}

// Validate validates this transform service state request
func (m *TransformServiceStateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExternalUserid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpenKfid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServiceState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransformServiceStateRequest) validateExternalUserid(formats strfmt.Registry) error {

	if err := validate.Required("external_userid", "body", m.ExternalUserid); err != nil {
		return err
	}

	return nil
}

func (m *TransformServiceStateRequest) validateOpenKfid(formats strfmt.Registry) error {

	if err := validate.Required("open_kfid", "body", m.OpenKfid); err != nil {
		return err
	}

	return nil
}

func (m *TransformServiceStateRequest) validateServiceState(formats strfmt.Registry) error {

	if err := validate.Required("service_state", "body", m.ServiceState); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this transform service state request based on context it is used
func (m *TransformServiceStateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransformServiceStateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransformServiceStateRequest) UnmarshalBinary(b []byte) error {
	var res TransformServiceStateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
