// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateCustomerServiceAccountRequest update customer service account request
//
// swagger:model UpdateCustomerServiceAccountRequest
type UpdateCustomerServiceAccountRequest struct {

	// media id
	MediaID string `json:"media_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// open kfid
	// Required: true
	OpenKfid *string `json:"open_kfid"`
}

// Validate validates this update customer service account request
func (m *UpdateCustomerServiceAccountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOpenKfid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateCustomerServiceAccountRequest) validateOpenKfid(formats strfmt.Registry) error {

	if err := validate.Required("open_kfid", "body", m.OpenKfid); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update customer service account request based on context it is used
func (m *UpdateCustomerServiceAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateCustomerServiceAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateCustomerServiceAccountRequest) UnmarshalBinary(b []byte) error {
	var res UpdateCustomerServiceAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
